// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n=Integer.parseInt(args[0]);
		double x;
		int btimes=0;
		int stimes=0;
		double ratio=0;
		for(int i=0; i<n; i++){
			 x= Math.random();
			 if(x>0.5){
				btimes++;
			 }
			 else{
				stimes++;
			 }
			 		}

			 ratio=(double)  btimes/stimes;
			 if (btimes==0||stimes==0){
				 System.out.println("> 0.5: " + btimes + " times");
			     System.out.println("<= 0.5: " + stimes + " times");
				}

             else{
				 System.out.println("> 0.5: " + btimes + " times");
			     System.out.println("<= 0.5: " + stimes + " times");
				 System.out.println("Ratio: " + ratio);

			 }

	    // Replace this comment with your code
	}
}
